### PR TITLE
feat(zeebe-plugin): persist endpoints and deployment config separately

### LINKED ISSUE #190: Handle Endpoint Configuration the same way as in Camunda Modeler
__Is your feature request related to a problem? Please describe.__

In _every_ tab, we use the same stored endpoint configuration. Note in the following screencast how the same configuration is filled into the modal, no matter what file we have opened.

Kapture 2020-04-02 at 11 02 20

We store a single endpoint configuration currently:

```json
 "DEPLOYMENT_CONFIG": {
    "audience": "",
    "camundaCloudClientId": "dump",
    "camundaCloudClientSecret": "dump",
    "camundaCloudClusterId": "dump",
    "connectionMethod": "camundaCloud",
    "deploymentName": "simple",
    "oauthClientId": "",
    "oauthClientSecret": "",
    "oauthURL": "",
    "rememberCredentials": true,
    "zeebeContactPointOauth": "",
    "zeebeContactpointSelfHosted": "0.0.0.0:26500"
 }
```

This does not match with the behavior we have in the Camunda Modeler, where we

* Diagram specification (deployment name) is saved per file
* Endpoint configuration is saved globally and referenced per file

__Describe the solution you'd like__

Align endpoint configuration persistence behavior with Camunda Modeler (details above).

__Additional Context__

Example Config how we have in the Camunda Modeler:

```json
{
  // ...
  "camundaEngineEndpoints": [
    {
      "authType": "bearer",
      "id": "0u3yvpk",
      "rememberCredentials": true,
      "token": "test",
      "url": "http://localhost:8080/rest"
    }
  ],
  "files": {
    "~/BPMN files/diagram_1.bpmn": {
      "deployment-tool": {
        "deployment": {
          "name": "diagram_1"
        },
        "endpointId": "0u3yvpk"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Create separate config places for per-file deployment configuration and zeebe endpoints.

Closes #190

### CODE REVIEW

**Comment by barmac** [comment]
So in the first case the config contains both OAuth and Camunda Cloud secrets. Also, the zeebeContactPointSelfHosted is always saved.

**Comment by pinussilvestrus** [comment]
I see. That's because we save the whole endpoint configuration no matter which connection type is chosen. That's not particularly an issue that comes with this PR, right? (cf. [original state](https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginModal.js#L190)) 

Would it be the expected behavior that I only save the endpoint configuration of the chosen connection type? If yes, we can fix that with that PR as well or simply open another issue for that.

**Comment by barmac** [comment]
So I'd expect that we save only a single endpoint configuration, which is its method and its data, but no other endpoint's data. I'm OK with if you open another issue, just let me know.

**Comment by pinussilvestrus** [comment]
Let's open another issue for that and handle that separately.

**Pull request merged**
