### PR TITLE
Latest issues

### LINKED ISSUE #54: Add support for message start event
• A user can model a message start event 
• A user can set the Message Name in the Properties panel (Subscription Correlation Key won't be used for message start events)

### PR DESCRIPTION
**Pull request by dominikhrn**
This fixes all current issues for the next zeebe release

- Remove payload mappings for merging parallel gateway sequence flows
- Remove output behavior from input/output mappings
- User can set output mappings for message events
- Support for non-interrupting message boundary event
- Support for non-interrupting timer boundary event
- Add support for timer start event
- Add support for message start event

Closes #54 #55 #56 #57 #58 #59 #60

### CODE REVIEW

**Comment by nikku** [comment]
@menski Could you or anyone on your team verify that things are working as you expect them?

```sh
git clone git@github.com:zeebe-io/zeebe-modeler.git
cd zeebe-modeler
git checkout latest-issues
npm install
npm run dev
```

**Comment by pinussilvestrus** [comment]
I'll give it a code review when I'm back @office (tomorrow) :+1:

**Comment by nikku** [comment]
> Just one thing: sendTask is currently not supported by Zeebe so if you could just remove it from the palette and morph menu, that'd be great. Thanks!

@MiguelPires Could you create a new issue for this one?

**Comment by nikku** [comment]
Thanks @dominikhrn, great work. :tada:

**Comment by MiguelPires** [comment]
Of course, here it is #63

**Pull request merged**
