### PR TITLE
Differentiate between auth and deployment target

### LINKED ISSUE #203: Differentiate between authentication method and deployment target
__What should we do?__

Differentiate between authentication method and the deployment target. 

Screenshot 2020-04-08 at 10 16 19

Flows:
1. User selects _Self-hosted_ => Authentication methods appear
2. User selects _Camunda Cloud_ => Camunda Cloud options appear

__Why should we do it?__

Currently, the deployment tool is mixing up authentication method (OAuth, no auth => _self-hosted_) and deployment target (_self-hosted_, Camunda Cloud). This might lead to confusion, especially as a self-hosted broker can also be secured by OAuth.

In case of Camunda Cloud there is no choice when it comes to auth, but for self-hosted Zeebe broker there might be mutliple options, including OAuth, no authentication, and, though not implemented yet, HTTP Basic and token authentication, which are already available in Camunda Modeler.

Child of #200

### PR DESCRIPTION
**Pull request by barmac**
Closes #203

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
One thing which I recognized, but is not related to this PR specifically (also discovered it on `develop`): The form is only showing errors when the field is empty, but no hint if wrong content

Kapture 2020-04-15 at 10 11 08

Is this intended?

**Comment by barmac** [comment]
I will have a look into this. Thanks for notice.

**Comment by pinussilvestrus** [comment]
Did a bit of root cause analysis and found out [that this check is broken](https://github.com/zeebe-io/zeebe-modeler/blob/develop/client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginModal.js#L202), I think after we refactored the configuration structure, cf. #197 

`fieldName` is filled with `endpoint.xxx`, but it checks for `xxx` only, so resolved `false` and not the correct error.

**Comment by pinussilvestrus** [comment]
We can open an issue for that little one or simply fix it with this PR, what do you think @barmac ?

**Comment by barmac** [comment]
I will have a fix for that. Thanks for hint!

**Comment by barmac** [comment]
OK I applied the fix. I still get funny result when changing target type (unknown error for cluster ID), but I guess we're not getting rid of this with any quick fix.

**Comment by pinussilvestrus** [comment]
I can not see what you mean, it works perfectly for me. Maybe you can open an issue for that if it's reproducible. Do you think it is blocking the release?

**Comment by barmac** [comment]
> I can not see what you mean, it works perfectly for me. Maybe you can open an issue for that if it's reproducible. Do you think it is blocking the release?

I think it is not blocking. I will create an issue for that.

**Comment by oguzeroglu** [comment]
glitch

I played with this a bit and there's this weird glitch when switching between the Auth types. I personally don't think this is a blocking issue. Should we maybe open an issue about this? Might be that we need to cancel the ongoing requests or something.

Besides that looks good, well done @barmac 👍

**Comment by oguzeroglu** [comment]
A suggestion about the glitch would be that: Do not try to validate the connection if auth fields are empty.

**Comment by barmac** [comment]
Yeah, I guess this will be implemented when we refactor the connection check.

**Comment by pinussilvestrus** [comment]
I guess that's the thing @barmac [was mention before](https://github.com/zeebe-io/zeebe-modeler/pull/206#issuecomment-613908480). Let's open an issue for that 👍 Maybe @oguzeroglu as you're able to reproduce it properly.

**Comment by oguzeroglu** [comment]
Ok, I'll open an issue.

**Comment by oguzeroglu** [comment]
https://github.com/zeebe-io/zeebe-modeler/issues/208

**Pull request merged**
