### PR TITLE
Pull in latest Camunda Modeler changes

### LINKED ISSUE #187: Pull in camunda-modeler@4-alpha.1 changes
__What should we do?__

Pull in [camunda-modeler@4-alpha.1](https://github.com/camunda/camunda-modeler/issues/1632) changes

```sh
$ npm run sync -- -t 'v4.0.0-alpha.1'
```

__Why should we do it?__

It pulls in important changes due to 
* UX improvements, #186 
* Branding update (Watermark, Loading spinner)

------

Child of https://github.com/zeebe-io/zeebe-modeler/issues/183

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Pulls in `camunda-modeler@4.0.0-alpha.1` changes. 

Closes #187 

---

**Todo**
* [x] <del>AppVeyor build is broken, cf. https://ci.appveyor.com/project/nikku/zeebe-modeler/builds/31814380#L72</del>

### CODE REVIEW

**Comment by oguzeroglu** [comment]
After updating the NodeJS version used with this commit, the Appvoyer lost access to Zeebe as well:

`Error fetching YAML configuration file from the repository. Make sure AppVeyor is authorized to access your gitHub account: AppVeyor GitHub App is not installed for account "zeeb..`

Let's not merge this yet.

**Comment by nikku** [comment]
Let's merge this :car:

**Comment by pinussilvestrus** [comment]
@barmac @oguzeroglu feel free to try it out, if nothing prevents us let's **merge** it

**Comment by oguzeroglu** [comment]
We need 1% more tests according to codecov 🤦‍♂

**Comment by nikku** [comment]
It's fine to merge in my point of view. We merge onto `develop`, after all.

**Comment by nikku** [comment]
Maybe we can even add a quick fix on top to bring back the buttons.

**Comment by oguzeroglu** [comment]
We can do a quick fix but then Maciej will have to revert the CSS changes after he integrates the new UI. If we're ok with having broken features temporarily in develop, IMO it's better to merge this without modifying anything.

**Comment by pinussilvestrus** [comment]
+1 of simply merging it, it's okay to have it this way in develop

**Pull request merged**
