### PR TITLE
Improve sync script

### LINKED ISSUE #247: Improve sync script
__What should we do?__

* [ ] Change merge strategy to squash
* [ ] Fetch only a single tag or branch from upstream repository, cf. https://stackoverflow.com/questions/45338495/fetch-a-single-tag-from-remote-repository
* [ ] Make sure to remove upstream tags and branches after sync regardless if it was successful or not

__Why should we do it?__

We want to avoid accidentally pushing upstream tags to the repo.

### PR DESCRIPTION
**Pull request by barmac**
* [x] Change merge strategy to squash
* [ ] Fetch only a single tag or branch from upstream repository, cf. https://stackoverflow.com/questions/45338495/fetch-a-single-tag-from-remote-repository

This is not implemented as I couldn't set it up correctly together with `git merge` (fetch with `--no-tags` made it impossible to refer to the tag later).

* [x] Make sure to remove upstream tags and branches after sync regardless if it was successful or not

This apparently works correctly after update of `simple-git`.

__Which issue does this PR address?__

Closes #247

__Definition of Done__

* [ ] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [ ] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [ ] passes Continuous Integration checks
* [ ] available as feature branch on GitHub
  * [ ] contains the cleaned up commit history
  * [ ] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [ ] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
> Fetch only a single tag or branch from upstream repository

I guess this is not so urgent anymore since we make sure to delete all un-related tags afterward in any case?

**Comment by barmac** [comment]
I've run a test sync on my machine and there were no Camunda Modeler tags present afterwards.

**Comment by pinussilvestrus** [comment]
I'd say it's cleaner to make sure you always have a fresh remote configuration when executing the sync. Therefore it makes sense, in case you have the remote already present, to delete and re-create it.

**Comment by barmac** [comment]
Ok, then I'll add a cleanup of the tags before sync is run.

**Comment by barmac** [comment]
Ready for review.

**Review by pinussilvestrus — APPROVED** [review]
🎬 

Regarding the missing possibility to only fetch a single branch/tag, should we open another issue for that?

**Comment by barmac** [comment]
I don't think it's necessary as we perform a full cleanup now.

**Comment by pinussilvestrus** [comment]
🚀  Thanks for improving the kind of outdated sync script 👍

**Comment by barmac** [comment]
I think there's still room for improvement when it comes to the ignored files. I'll have another issue for that.

**Pull request merged**
